apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  ports:
  - port: 808
    protocol: TCP
    targetPort: 8080
  selector:
    app: accounts
  type: ClusterIP
status:
  loadBalancer: {}
